server:
  port: 8082
spring:
  application:
    name: servie-consumer

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

#hystrix:
# command:
#   default:
#     execution:
#       isolation:
#           thread:
#              timeoutInMillisecond: 5000
feign:
 hystrix:
   enabled: true
